# Generated by Django 4.2.4 on 2023-08-17 23:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0002_notifications_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='when',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
