# Generated by Django 4.2.4 on 2023-08-16 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Community name')),
                ('region', models.CharField(max_length=255, verbose_name='Region')),
                ('created_by', models.CharField(max_length=255, verbose_name='Created by')),
                ('verif_code', models.CharField(max_length=9, unique=True, verbose_name='Verification code')),
                ('visibility', models.CharField(choices=[('private', 'private'), ('public', 'public')], default='private', max_length=20, verbose_name='Visibility')),
                ('description', models.TextField(verbose_name='Community description')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Created on')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.CharField(max_length=255, verbose_name='Community')),
                ('title', models.CharField(max_length=255, verbose_name='Activity title')),
                ('description', models.TextField(verbose_name='Activity description')),
                ('planned_date', models.DateField(blank=True, verbose_name='Planned date')),
                ('status', models.CharField(choices=[('PL', 'planned'), ('OG', 'ongoing'), ('Co', 'completed'), ('Ca', 'cancelled')], default='planned', max_length=20, verbose_name='Activity status')),
                ('summary', models.TextField(blank=True, verbose_name='End of activity summary')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.CharField(max_length=255, verbose_name='Member to')),
                ('username', models.CharField(max_length=255, verbose_name='Member username')),
                ('date_joined', models.DateField(auto_now_add=True, verbose_name='Joining date')),
            ],
        ),
    ]
