# Generated by Django 4.2.4 on 2023-08-09 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='verif_code',
            field=models.CharField(max_length=9, unique=True, verbose_name='Verification code'),
        ),
    ]
