# Generated by Django 4.2.4 on 2023-08-10 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_alter_community_verif_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='verif_code',
            field=models.CharField(default='DQK9IZRE', max_length=9, unique=True, verbose_name='Verification code'),
        ),
        migrations.AlterField(
            model_name='community',
            name='visibility',
            field=models.CharField(choices=[('private', 'private'), ('public', 'public')], default='private', max_length=20, verbose_name='Visibility'),
        ),
    ]
